# Generated by Django 4.2 on 2023-04-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, to='askme.tag'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(null=True)),
                ('answer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='askme.answer')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='askme.profile')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='askme.question')),
            ],
        ),
    ]
